// packages/manager/src/components/login-form.tsx
'use client'

import { Alert, AlertDescription } from '@/components/ui/alert'
import { AlertCircle, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { fetchToken } from '@/api/user'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import type React from 'react'
import { UnauthorizedError } from '@/errors/unauthorized'
import { useNavigate } from '@tanstack/react-router'
import { useState } from 'react'
import useUserStore from '@/stores/user'

export function LoginForm() {
  const navigate = useNavigate()
  const { login } = useUserStore()
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')
  const [formData, setFormData] = useState({
    username: '',
    password: '',
  })

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')

    // Validate form
    if (!formData.username || !formData.password) {
      setError('Please fill in all fields')
      return
    }

    setIsLoading(true)

    try {
      const data = await fetchToken(formData.username, formData.password)
      if (login(data)) {
        navigate({ to: '/manage/reset' })
      } else {
        navigate({ to: '/manage/redirect' })
      }
    } catch (error) {
      if (error instanceof UnauthorizedError) {
        setError('Invalid email or password')
      } else {
        setError('An error occurred. Please try again.')
      }
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Login</CardTitle>
      </CardHeader>

      <form onSubmit={handleSubmit}>
        <CardContent className="space-y-4 py-4">
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input
              id="username"
              name="username"
              type="text"
              value={formData.username}
              onChange={handleChange}
              disabled={isLoading}
              required
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              name="password"
              type="password"
              value={formData.password}
              onChange={handleChange}
              disabled={isLoading}
              required
            />
          </div>
        </CardContent>
        <CardFooter>
          <Button className="w-full" type="submit" disabled={isLoading}>
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Signing in...
              </>
            ) : (
              'Sign in'
            )}
          </Button>
        </CardFooter>
      </form>
    </Card>
  )
}

// packages/manager/src/components/login-form/LoginForm.vue
<script setup lang="ts">
import { Alert, AlertDescription } from "../ui/alert";
import { AlertCircle } from "lucide-vue-next";
import { Button } from "../ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../ui/card";
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "../ui/input";
import { ref } from "vue";
import { Spinner } from "../ui/spinner";
import { toTypedSchema } from "@vee-validate/zod";
import { useAuthStore } from "@/stores/auth.store";
import { useForm } from "vee-validate";
import { useRouter } from "vue-router";
import * as z from "zod";

const { login } = useAuthStore();
const router = useRouter();

const error = ref<string | null>(null);
const isLoading = ref(false);

const loginSchema = toTypedSchema(
  z.object({
    username: z.string().min(1, "Username is required"),
    password: z.string().min(1, "Password is required"),
  }),
);

const { isFieldDirty, handleSubmit } = useForm({
  validationSchema: loginSchema,
});

const onSubmit = handleSubmit(async ({ username, password }) => {
  isLoading.value = true;

  try {
    await login(username, password);
    router.push("/dashboard");
  } catch (e) {
    if (e instanceof Error) {
      error.value = e.message;
    } else if (typeof e === "string") {
      error.value = e;
    } else {
      error.value = "Unknown error";
    }
  }

  isLoading.value = false;
});
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Login</CardTitle>
    </CardHeader>

    <form @submit="onSubmit">
      <CardContent class="space-y-4">
        <Alert v-if="error" variant="destructive">
          <AlertCircle class="h-4 w-4" />
          <AlertDescription>{error}</AlertDescription>
        </Alert>

        <FormField
          v-slot="{ componentField }"
          name="username"
          :validate-on-blur="!isFieldDirty"
        >
          <FormItem>
            <FormLabel>Username</FormLabel>
            <FormControl>
              <Input
                type="text"
                :disabled="isLoading"
                v-bind="componentField"
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        </FormField>

        <FormField
          v-slot="{ componentField }"
          name="password"
          :validate-on-blur="!isFieldDirty"
        >
          <FormItem>
            <FormLabel>Password</FormLabel>
            <FormControl>
              <Input
                type="password"
                :disabled="isLoading"
                v-bind="componentField"
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        </FormField>
      </CardContent>
      <CardFooter>
        <Button v-if="isLoading" class="w-full mt-4" type="submit" disabled>
          <Spinner />
          Signing in...
        </Button>
        <Button v-else class="w-full mt-4" type="submit"> Sign in </Button>
      </CardFooter>
    </form>
  </Card>
</template>
